# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f08b14247b3c88690a48042216198e5b1fb806636c44e863544a10187795c343cbaf44dd1eac4628cc6c066a371c9aedda1567fba1da6faa029b03f08cffa3c

test:
  secret_key_base: 9a4415832b114ed7e04b146a0920596885381d6210f142f3a8341253421d7054e02b9bdc45f66bca17cc9da06ad0faca2570e208dbfec0307ccfc658684e3a8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
